# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            !~/.cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Extract branch name
        shell: bash
        run: |
          echo Setting branch name from GITHUB_REF: $GITHUB_REF
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/pull/})"
        id: extract_branch

      - name: Get latest commit hash
        shell: bash
        run: |
          echo Setting commit hash: $(git rev-parse HEAD)
          echo "##[set-output name=hash;]$(git rev-parse HEAD)"
        id: commit_hash

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install packages
        run: yarn install

      - name: Build the Gatsby website
        run: yarn build

      # Deploy prebuilt stuff to Netlify
      - name: Publish to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './public'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Merge ${{ steps.extract_branch.outputs.branch }} into master @ ${{ steps.commit_hash.outputs.hash }}'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
